#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-aliyun-openapi-java-sdk
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-aas/2.1.0/aliyun-java-sdk-aas-2.1.0-sources.jar
Source0  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-aas/2.1.0/aliyun-java-sdk-aas-2.1.0-sources.jar
Source1  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.pom
Source3  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.jar
Source4  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.pom
Source5  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.jar
Source6  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.pom
Source7  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.jar
Source8  : https://repo.maven.apache.org/maven2/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-aliyun-openapi-java-sdk-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-aliyun-openapi-java-sdk package.
Group: Data

%description data
data components for the mvn-aliyun-openapi-java-sdk package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-aas/2.1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-aas/2.1.0/aliyun-java-sdk-aas-2.1.0-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-aas/2.1.0/aliyun-java-sdk-aas-2.1.0-sources.jar
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.jar
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-core/3.4.0/aliyun-java-sdk-core-3.4.0.pom
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.jar
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ecs/4.2.0/aliyun-java-sdk-ecs-4.2.0.pom
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.jar
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-ram/3.0.0/aliyun-java-sdk-ram-3.0.0.pom
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.jar
/usr/share/java/.m2/repository/com/aliyun/aliyun-java-sdk-sts/3.0.0/aliyun-java-sdk-sts-3.0.0.pom
